___

<a href='https://www.instagram.com/lanlearning/'> <img src='../pyimages/logosmall.png' width="100" height="100"/></a>
___
<center>Copyright LanLearning 2020</center>




# Welcome back!

# Icebreaker: What was you favorite cartoon as a kid? 


# Today's Agenda:
## 1. DS News + Projects
## 2. Python 5 Notebook
## 3. Kahoot
## 4. Project Showcase
## 5. Reminders + Guest Speaker Groundrules

<img src='../pyimages/waz.png' width="350"/>



## Breakout Room 1: 
1. Psychological aspects, combining models such as bots. 
2. 23&me, data based on people input, height weight and using that to find chances of diseases; diagnose people

## Breakout Room 2:
1. Coronavirus–see how trend is spreading, analyze spread of virus using data
2. Data Science not always perfect, undercoverage; testing is expensive; drawback

## Breakout Room 3:
1. Article - six ways data science changed the world; impacted different aspects of the world
    - healthcare: track in real time, more accurate over time
    - road travel
2. Theorem called "Central Limit Theorem", 
    - Wanna find the average age of sport drinkers in the world, using that data from one sample, and use it to represent the entire population
    - Bell-curves and learning more about your population
    
## Breakout Room 4: 
1. Article–AI learned form lung CT scan; image recognition!!! 
    - in China, AI used to collect data on testing, the more testing done, more accurate their results were
    - better diagnose of patients 
    
## Breakout Room 5:
1. Five Data Science projects to get you hired in 2020
2. Data cleaning takes a lot of time; importing data (using SQL), making sure everything is correct
3. Stood out: Find trends in terms of correlation of data and relating back to how business functions
**Communication** is a key in DS!! Know about your audience and presenting visuals





This workbook is designed for you to learn the basics of Python. There will be a few workbooks like this one designed to help you learn Python in the following parts. 

Please follow the notebooks in the steps below because they are designed to follow from one another:

- Part 1: Basic Data Types
- Part 2: Advance Data Types
- Part 3: Functions
- Part 4: Python Processes
- Part 5: Numpy

## A different type of Python:

In the previous notebook, we covered some of the fundamentals of the Python language. These are built-in things that you can do with Python. 

While the built-in Python tools are powerful enough for us to do some complicated things, there's still a lot that's left to use and uncover. 

A lot of Data Science tools are coded by professionals and saved on the internet in the form of **libraries**. 

### Libraries:
A **library** is a resuable piece of code that you can use for your projects or various other needs. A Python library is built using Python, and all of the code in the library will be in the Python syntax. 

<br>
<img src='../pyimages/lib.jpg' width="800"/>
<center> Inside look of UC Berkeley Doe Library </center>
<br>

#### Documentation:
A library is often included with **documentation**, which is like a cheat sheet that tells you what certain functions in the library do. 

**In this notebook** we will be doing math using **NumPy**, which is one of the most widely used math libraries. Next week, we will be using **Pandas**, which is a super useful Data Science library used to manipulate data. 

## Numpy: 
Numpy is a math library that is used to compute and operate on numbers and arrays of numbers. In this notebook, I will introduce Numpy as a tool to help us do math, but you can explore the other features of Numpy on your own! 

Documentation for it: https://numpy.org/doc/1.18/

<br>
<img src='../pyimages/numpy.png' width="300"/>
<br>

### Importing Numpy:
Like all libraries, in order to use Numpy, we must import it, and the following line does that for us:

In [ ]:
import numpy

Typically, you want to give your library a nickname so it's easier to refer to. Let's give our imported library the nickname ```np``` by using ```as``` in our import statement:

In [3]:
import numpy as np

*Note*: Running import statements doesn't really return anything, so don't worry about why there's nothing after running the lines.

## Some examples:

Whenever you use a function from numpy, you always need to add the ```np``` before the function name. Then leave a dot and call the function you want to use. 

The dot represents the fact that the function is a part of the numpy library, which is used once we use the ```.``` and ```np```. 

Then you want to pass in the parameter as you do in a usual function.

In [ ]:
# .sqrt() takes the square root of the parameter
np.sqrt(4)

In [ ]:
# .round() will round the first parameter to the second parameter number of decimal places
np.round(3.57688283, 4)

In [ ]:
# .round() if you only pass in one parameter, it will round it to the nearest integer
np.round(3.56788283)

So you might be **wondering** how I know that ```.round()``` works the way it does? I can read how these functions work from the documentation. 

Check it out: https://numpy.org/doc/stable/reference/generated/numpy.round_.html?highlight=numpy.round#numpy.round_

Another great place to get information about your code is StackOverflow,  people post really detailed explanations here: https://stackoverflow.com/questions/22261843/python-np-round-with-decimal-option-larger-than-2

## Why Use Numpy?
The most important feature (and one of the main reasons why numpy is used) is for its **element by element computation**. 

Before jumping into that, feel free to explore more about the Numpy library just to see all the cool things you can do with it. (You can do a lot of stuff with Stats and Probabilities as well, things like random sampling; however, we won't cover those during this summer camp.)


### Element-by-Element Computation:
I think the best way for you to understand element by element computation is through an example:

Element by Element computation is when you have two lists, say ```[1, 2, 3]``` and ```[3, 2, 1]```, and you want to add the elements of the two lists according to their index so you get ```[4, 4, 4]```. Essentially, this is ```[1 + 3, 2 + 2, 3 + 1]```.

Let's try it out:

In [1]:
[1, 2, 3] + [3, 2, 1]

[1, 2, 3, 3, 2, 1]

#### Yeah... Turns out you can't simply add them together... 

So you're going to need to try something complicated... such as a for loop.

**However**, if these lists were arrays in Numpy, then you can simply add them together:

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
[1, 2, 3]

[1, 2, 3]

In [7]:
np.array([1, 2, 3]) + np.array([3, 2, 1]) + np.array([100, 100, 100]) # yay!!

array([104, 104, 104])

<br>
<img src='../pyimages/scipy.png' width="800"/>
<center> From SciPy Lecture Notes </center>
<br>

Notice how this time when you added the two lists together, you got what you wanted. 




In [17]:
# to turn a list int a Numpy array, use the np.array() function
np.array(['Turn', 3, True, 4.5])

array(['Turn', '3', 'True', '4.5'], dtype='<U4')

In [9]:
# to turn a list int a Numpy array, use the np.array() function
np.array([6, 5, 4, 3, 2, 1])

array([6, 5, 4, 3, 2, 1])

In [13]:
np.array([1, 2, 0, 0]) + np.array([1, 2, 3, 4])

array([2, 4, 3, 4])

In [11]:
len(np.array([1, 2, 3, 4]))

4

In [12]:
np.array(['hi', 'hi']) + np.array(['Daniel', 'Mario'])

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('<U6')) -> dtype('<U6')

In [19]:
# modulus operator aka % is used for remainder

25 % 3

1

You can tell its a numpy array because of what is returned ```array(['Turn', 'this', 'into', 'a', 'Numpy', 'array!'], dtype='<U6')```

Here ```dtype='<U6'``` tells you what the data type within the array is. 

**Using np.arange() to create a numpy array of numbers**

You can use the function .arange() to quickly create an array of numbers. The method .arange() can have at most 3 parameters but has to have at least one parameter.

One way is to write np.arange(start, stop, step). This will create an array of numbers starting with start, going up in increments of step, and going up to but excluding stop.

In [ ]:
first_array = np.arange(0, 10, 2) 
first_array

A second way is to write np.arange(start, stop)

In [ ]:
second_array = np.arange(1, 9)
second_array

The final way is np.arange(stop)

In [ ]:
third_array = np.arange(7)
third_array

**Numpy has this ability to treat computation or arrays element-by-element, and that's where the power of Numpy comes from**.

You can do all sorts of computation, not just addition:

In [ ]:
np.array([1, 2, 3]) - np.array([3, 2, 1])

In [ ]:
np.array([1, 2, 3]) * np.array([3, 2, 1])

In [ ]:
np.sqrt([1, 2, 3])

## Why does this matter:

When we get to Pandas, the ability to do element-by-element math becomes important. This will allow us to simply add two lists of our data together. 

Hold tight on seeing this come to fruition; it'll be a big part of our Pandas lessons.

## Something random!

<br>
<img src='../pyimages/coin.png' width="400"/>
<center> Source: JustFlipACoin.com </center>
<br>


With the Numpy library, you can do random stuff, such as simulating the toss of a coin. 

Use the np.random.choice function:

In [ ]:
np.random.choice(['Heads', 'Tails'])

Keep running it a few times, you should start seeing different outputs.

Here I'm going to toss 10 coins:

In [ ]:
np.random.choice(['Heads', 'Tails'], 10)

## Recap
- numpy is an extremely useful math library in Python, to import it and give it a shorter nickname write ```import numpy as np```
- to call a function that is part of the numpy library, use the syntax np.function_name(any_parameters)
- ex: np.sqrt(4), np.round(3.456, 2)
- one important and advantageous feature of numpy is its element by element computation, lists are not capable of element by element computation and can be turned into a numpy array by using the function np.array()
- ex: np.array([1, 2, 3]) * np.array[2, 2, 2] ---> array(2, 4, 6)
- can create an array of numbers by using the function np.arange(start, stop, step), which needs to have at least 1 parameter (stop), at most 3 parameters
- ex: np.arange(0, 6, 2) ---> array(0, 2, 4)
- you can use the function np.random.choice(list_of_choices, number_of_times_chosen) to randomly choose a value from a list of values a specified number of times
- ex: np.random.choice(['Heads', 'Tails'], 10)
- website for numpy documentation: https://numpy.org/doc/1.18/
         

## Guest Speaker Outline! 

<img src='../pyimages/daphne.JPG' width="600"/>

# 1. Wear something Disney! 
## Show some spirit! But be professional, no hats!
<img src='../pyimages/mulan.jpg' width="600"/>

## Outline: We will start at 1:03!!!!
### 1. Give Daphne a progress update of Week 1 + Introduce Daphne
### 2. She'll present for 30-45 mins. 
### 3. Q + A
1. Good change to ask her for DS project ideas. 
2. How to get started or more epxerienced with DS + Coding. 
3. Where to find opportunities + people to learn more about DS from. 
4. More technical questions are great! Why ML is important or ethical implications of her work etc.!

# End

That's all for now with this Numpy notebook. 

Feel free to mess around with and solidy your understandings with code cells! 

See you in the next notebook!

### About this notebook: 
Developed by: <br>
**Milan Butani** <br>
**Kyra Yee** <br>


#### Your feedback and learning are important to us. Please leave us a feedback on our work! 

Feedback link: https://forms.gle/XbC6dxXbqnP9JihV6